### ISSUE TITLE
Make use of openh264 instead of x264 ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [Samsung/ChromiumGStreamerBackend#12]
Openh264 is an open source and free implementation of the h264 codec backed by Cisco and mozilla wich perform very well. 
Sorry if say Something of stupid I'm Just a lambda user :p also thanks for your welcome work on gallium 3d !!

**Comment by LifeIsStrange** [comment]
Oh here the link of the github : https://github.com/cisco/openh264

**Comment by JulienIsorce** [comment]
It should be a request to GStreamer bug tracker: https://bugzilla.gnome.org/enter_bug.cgi?product=GStreamer

Also note that GStreamer already has a plugin that wraps openh264, see http://cgit.freedesktop.org/gstreamer/gst-plugins-bad/tree/ext/openh264/

**Comment by JulienIsorce** [comment]
If my last comment did not answer your question please re-open the issue and provide more context. Thx
