### ISSUE TITLE
Why not create a servo gstreamer backend ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [Samsung/ChromiumGStreamerBackend#13]
The new servo layout engine is the future, it outperform gecko and blink by up to 25x ! And is more secure (rust inside) 
So, Samsung already work with mozilla for servo and plan to create a New modern browser for Android at the beggining based on blink but is it planned that it will switch to servo when servo will be quite stable :)  (Q2/3 2016 for Android and 2017/18 for desktop because desktop websites are more complex in general). 
So it's on the interest of Samsung and of the humanity (the free software magic). 
Sorry for my poor english and thanks for developing free software =).

**Comment by JulienIsorce** [comment]
ChromiumGStreamer is not a media backend for Blink but for Chromium. So the target here is really Chromium, not blink. Note that blink does not have any media backend, it just provides the blink:WebMediaPlayer interface.

You should suggest the idea to the maintainers of this browser based on servo.

**Comment by JulienIsorce** [comment]
If the my last comment did not answer your question please re-open and provide additional context. Thx
