### ISSUE TITLE
Building with chrome_sandbox option

### ISSUE THREAD

**Issue by jongheeyun** [Samsung/ChromiumGStreamerBackend#15]
Hi,

src$ ninja -C out/Release chrome chrome_sandbox -j30
ninja: Entering directory `out/Release'
ninja: error: unknown target 'chrome_sandbox'

I met error when using chrome_sandbox option on Mac. I could build with chrome only.
Is this an invalid option or did I miss something?

Thanks,
Steve.

**Comment by CapOM** [comment]
Hi Steve, 

I never tried on Mac. If you type: "ninja -C out/Release chrom" without pressing enter, then press tab+tab for auto completion. On Linux it prints :

chrome  
chrome_initial
chrome_unscaled_resources
chromium_builder_nacl_win_integration
chrome-wrapper
chrome_internal_resources_gen
chromedriver
chromium_builder_perf
chrome.1
chrome_material_100_percent.pak
chromedriver_lib
chromium_builder_tests
chrome.isolated
chrome_material_200_percent.pak
chromedriver_tests
chromium_builder_webrtc
chrome_100_percent.pak
chrome_resources
chromedriver_unittests
chromium_gpu_builder
chrome_200_percent.pak
chrome_run
chromedriver_unittests.isolated
chromium_gpu_debug_builder
chrome_api 
---> chrome_sandbox
chromedriver_unittests_run 
chromium_swarm_tests
chrome_api_registration
chrome_settings_proto_generated_compile  chromium_builder_asan                    chromoting_test_driver
chrome_app_unittests
chrome_strings
chromium_builder_chromedriver
chromotocol_proto_lib
chrome_extra_resources
chrome_ui_string_overrider_factory
chromium_builder_nacl_sdk                

Including "chrome_sandbox" in this list

Hope this help,
Cheers
Julien

**Comment by jongheeyun** [comment]
Thanks, for reply.
I close this issue.
Steve.
