### ISSUE TITLE
Awesome but chrome is full of backdoors.... 

### ISSUE THREAD

**Issue by LifeIsStrange** [Samsung/ChromiumGStreamerBackend#2]
Yes there are chromium but the people use chrome instead of chromium or Iron... 
So there is a port planned for implement gstreamer on Firefox ? :) 
Sorry for bad english.

**Comment by sdroege** [comment]
Firefox already supports GStreamer and uses it on Linux by default (and can use it on OSX/Windows if you compile it yourself).

**Comment by LifeIsStrange** [comment]
Oh thank you sdroege ! 
Also sorry an other question who take your time (you are not obligated ton answer me) gstreamer have à Daala draft implementation ?

**Comment by sdroege** [comment]
@LifeIsStrange yeah, I wrote one a few years ago here: http://cgit.freedesktop.org/gstreamer/gst-plugins-bad/tree/ext/daala
I don't know if it compiles against the latest Daala API, it probably needs some updates.

_Update_: Actually it still compiles and just works with latest Daala

**Comment by sdroege** [comment]
Note that Daala is not production ready yet, and that streams you create now are most likely not going to work with the final format.

**Comment by LifeIsStrange** [comment]
OK thank you so much sdroege ! And I know that Daala still need one year of stabilisation :)

**Comment by sdroege** [comment]
If you want to discuss more GStreamer related things, better let's move this to the GStreamer developers mailing list here: http://gstreamer.freedesktop.org/lists/

**Comment by LifeIsStrange** [comment]
Yes, thanks !

**Comment by JulienIsorce** [comment]
Thx for your remarks, if you have further request please open a new issue.
